version: "3.8"

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: market_place
      MYSQL_USER: stepan
      MYSQL_PASSWORD: secret2
    volumes:
      - ./dbdata:/var/lib/mysql/

